[package]
name = "unknown-wallet"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
unknown-interfaces.workspace = true
unknown-primitives.workspace = true
unknown-keys.workspace = true
unknown-notes.workspace = true
unknown-tree.workspace = true
unknown-encryption.workspace = true
unknown-tx.workspace = true
unknown-prover-dev.workspace = true
unknown-antispam-pow.workspace = true
thiserror.workspace = true

[lints]
workspace = true
