[package]
name = "unknown-prover-dev"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
unknown-interfaces.workspace = true
unknown-primitives.workspace = true
unknown-keys.workspace = true
unknown-notes.workspace = true
unknown-tree.workspace = true

[lints]
workspace = true
