[package]
name = "unknown-tx"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
unknown-interfaces.workspace = true
unknown-primitives.workspace = true
unknown-encryption.workspace = true
unknown-antispam-pow.workspace = true
unknown-antispam-quota.workspace = true
thiserror.workspace = true

[dev-dependencies]
unknown-prover-dev.workspace = true

[lints]
workspace = true
